apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  namespace: all-in-market
  labels:
    app: gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      name: gateway-api
      labels:
        app: gateway-api
    spec:
      containers:
        - name: gateway-api
          image: albertsereda/all-in-market-gateway-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_CONFIG_IMPORT
              value: file:/config/
          volumeMounts:
            - name: gateway-api-config
              mountPath: /config
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: gateway-api-config
          configMap:
            name: gateway-api-config
      restartPolicy: Always
